export const eventosDemonstracao = [
  {
    id: 1,
    titulo: "Arrecadação de Alimentos",
    tipo: "Arrecadação",
    descricao: "Ajude famílias carentes da região central.",
    data_hora_inicio: "20/05/2024 08:00",
    data_hora_fim: "20/05/2024 14:00",
    local: "Centro",
  },
  {
    id: 2,
    titulo: "Mutirão de Limpeza",
    tipo: "Organização",
    descricao: "Limpeza da praia e conscientização ambiental.",
    data_hora_inicio: "22/05/2024 10:00",
    data_hora_fim: "22/05/2024 12:00",
    local: "Praia do Sol",
  },
  {
    id: 3,
    titulo: "Aula de Reforço",
    tipo: "Preparação",
    descricao: "Voluntários para ensinar matemática para crianças.",
    data_hora_inicio: "25/05/2024 14:00",
    data_hora_fim: "25/05/2024 15:30",
    local: "Escola Municipal",
  },
  {
    id: 4,
    titulo: "Campanha de Doação de Sangue",
    tipo: "Doação",
    descricao: "Parceria com o Hemocentro para salvar vidas.",
    data_hora_inicio: "28/05/2024 09:00",
    data_hora_fim: "28/05/2024 17:00",
    local: "Hospital Santa Casa",
  },
  {
    id: 5,
    titulo: "Oficina de Reciclagem",
    tipo: "Preparação",
    descricao: "Ensine crianças a transformar lixo em arte.",
    data_hora_inicio: "30/05/2024 14:00",
    data_hora_fim: "30/05/2024 16:00",
    local: "Centro Comunitário",
  },
  {
    id: 6,
    titulo: "Passeio com Cães do Abrigo",
    tipo: "Organização",
    descricao: "Dê carinho e exercício para animais resgatados.",
    data_hora_inicio: "01/06/2024 08:30",
    data_hora_fim: "01/06/2024 11:00",
    local: "Abrigo Patas Felizes",
  },
  {
    id: 7,
    titulo: "Distribuição de Agasalhos",
    tipo: "Doação",
    descricao: "Entrega de cobertores e roupas para moradores de rua.",
    data_hora_inicio: "03/06/2024 20:00",
    data_hora_fim: "03/06/2024 23:00",
    local: "Praça da Sé",
  },
];
